name: CI
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - run: python3 -m unittest discover -s tests -v
      - run: python3 agent/e2e_test_agent.py --help
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72
      - run: nix flake check --no-update-lock-file
      - run: nix run . -- --help
